development:
  adapter: postgresql
  encoding: unicode
  database: qa-web-app_development
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: qa-web-app_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: qa-web-app_production
  pool: 5
  username:
  password: